dynamic data loading from the database
reduct-nepal/seep pull request #27
Opened 2020-10-29 10:43 UTC by Anurodhyadav

Loading of real data from the database done.

2020-10-29 11:00 UTC, Drishtantr requested changes

2020-10-30 02:09 UTC, shakyaprasen commented on src/views/SignIn.vue
> +                this.$router.replace({ name: 'TempAdmin' });
any reason for using $router.replace instead of $router.push ?

2020-10-30 02:09 UTC, shakyaprasen commented on src/views/Test.vue
> +                    maxgrammerAccuracy: Math.max.apply(0, this.grammaraccuracyNet),
grammar spelling inconsistent

2020-10-30 02:10 UTC, shakyaprasen approved these changes

2020-10-30 08:19 UTC, Drishtantr approved these changes

2020-10-30 09:25 UTC, shakyaprasen commented
pelase resolve the conflicts before merging

2020-10-30 09:39 UTC, merged